#!/bin/sh
PATH=$PATH:/sbin:/usr/sbin

echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] killing others tunnel daemons ...
ps | grep '/bin/sh /usr/bin/zZZ-novartis-intra-tunnel' | grep -v $$ | grep -v grep | kill_from_ps

while [ 1 ]; do
	echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] ---------------------------------------
	
	echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] verifying port 42022 available ...
	out=$(netstat -nltp 2>/dev/null | grep 42022 | wc -l)
	if [ $out -eq 0 ]; then
	    echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] port 42022 NOT available !!!
	    echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] EXIT
	    exit 1
	fi

	status=OK

	if [ $status = OK ]; then 
		echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] verifying tun100 is free ...
		if [ $(ifconfig -a | grep tun100 | wc -l) -ne 0 ]; then
			echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] killing tun100 owner ...
			ps | grep 'ssh -f -p 42022 -w 100:99 root@localhost' | grep -v grep | kill_from_ps
		fi
		sleep 1
		if [ $(ifconfig -a | grep tun100 | wc -l) -ne 0 ]; then
			echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] Can NOT free tun100 !!!
			status=KO
		fi
	fi

	if [ $status = OK ]; then 
		echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] cleaning up remote host ...
		ssh -p 42022 root@localhost /root/bin/zZZ-ssh-clean-up.sh
		if [ $? -ne 0 ]; then
			status=KO	
		fi	
	fi

	if [ $status = OK ]; then 
		echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] creating tunnel ...
		ssh -f -p 42022 -w 100:99 root@localhost /root/bin/zZZ-ssh-tunnel-up.sh

		echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] configuring interface ...
		ifconfig tun100 p1iw pointopoint prod2

		echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] adding route ...
		route add -net 172.18.1.128 netmask 255.255.255.192 gw p1iw tun100

		if [ $(iptables -t nat -L POSTROUTING -v | grep tun100 | wc -l) -eq 0 ]; then
			echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] adding NAT ...
			iptables -t nat -A POSTROUTING -o tun100 -j MASQUERADE
		fi
		firstRun=1
		pingResponse=1
		pingResponseHA=0
		while [ $pingResponse -ne 0 ];do
		  if [ $pingResponseHA -eq 0 ]; then
			statusGWHA=OK
			echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] verifying tun98 is free ...
			if [ $(ifconfig -a | grep tun98 | wc -l) -ne 0 ]; then
				echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] killing tun98 owner ...
				ps | grep 'ssh -f -w 98:97 gw-ha' | grep -v grep | kill_from_ps
			fi
			sleep 1
			if [ $(ifconfig -a | grep tun98 | wc -l) -ne 0 ]; then
				echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] Can NOT free tun98 !!!
				statusGWHA=KO
			fi

			if [ $statusGWHA = OK ]; then 
				echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] cleaning up remote host GW-HA ...
				ssh gw-ha /root/bin/zZZ-ssh-clean-up-ha.sh
				if [ $? -ne 0 ]; then
					statusGWHA=KO	
				fi	
			fi

			if [ $statusGWHA = OK ]; then 
				echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] creating tunnel GW-HA ...
				ssh -f -w 98:97 gw-ha /root/bin/zZZ-ssh-tunnel-up-ha.sh

				echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] configuring interface GW-HA ...
				ifconfig tun98 192.168.41.2 pointopoint 192.168.41.3

				echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] adding routes GW-HA ...
				route add -net 192.168.40.0 netmask 255.255.255.0 gw 192.168.41.3
				route add -net 192.168.60.0 netmask 255.255.255.0 gw 192.168.41.3
				route add -net 192.168.65.0 netmask 255.255.255.0 gw 192.168.41.3
			fi
		  fi

		  sleep 3
		  pingResponse=$(ping -c 5 prod2 | grep 'received' | awk -F',' '{ print $2 }' |	awk '{ print $1 }')
		  if [ $firstRun -eq 1 ]; then
			echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] PING RESPONSE: $pingResponse
		  fi

		  pingResponseHA=$(ping -c 5 192.168.41.3 | grep 'received' | awk -F',' '{ print $2 }' | awk '{ print $1 }')
		  if [ $firstRun -eq 1 ]; then
		  	echo \[SKB-OpenWrt-$$-$(date +"%Y-%m-%d-%H:%M:%S")] PING RESPONSE HA: $pingResponseHA
			firstRun=0
		  fi

		done
	else
		sleep 3
	fi
done

