#!/bin/bash
 
IF=$1
STATUS=$2

ip addr show wlan0 | grep inet | grep -v inet6 > /tmp/$IF.txt

if ! diff /tmp/$IF.txt /home/raf/Dropbox/$IF.txt 1>/dev/null; then
    cp /tmp/$IF.txt /home/raf/Dropbox/$IF.txt
    logger -s "ip to dropbox"
fi


